# Generated by Django 4.2.8 on 2023-12-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='owner',
        ),
    ]
